### ISSUE TITLE
RPC Internal error

### ISSUE THREAD

**Issue by mcrconference** [alkhachatryan/laravel-web-console#13]
Hi, I am writing to you for a problem I have after installing your library. It works correctly locally, but if I install the files remotely I get the error

 [ERROR] RPC : Internal error (Undefined variable: pipes)

Can you help me ? Thanks

**Comment by alkhachatryan** [comment]
Hello @mcrconference 

Could you please provide more information how to reproduce the error?

**Comment by mcrconference** [comment]
Of course, I simply uploaded all the Laravel content to shared hosting after clearing the cache. The site opens correctly, the webconsole asks me for a login and password and gives me access, when I launch a command, the error appears

**Comment by alkhachatryan** [comment]
@mcrconference  send the backtrace.

**Comment by mcrconference** [comment]
sorry I did not understand what you mean

**Comment by alkhachatryan** [comment]
You should see something like this:
![image](https://user-images.githubusercontent.com/22774727/81827556-ed9f1b00-9549-11ea-88bd-51754b2833d9.png)


The "lines of the error"

**Comment by alkhachatryan** [comment]
This is not the backtrace.

Open the Development tool of the browser (F12)
Goto Network
Run the command in the terminal again
Open the request response page and you'll see the backtrace.

Or copy the log content here.

**Comment by mcrconference** [comment]
<img width="1280" alt="Schermata 2020-05-13 alle 16 56 13" src="https://user-images.githubusercontent.com/65294947/81828970-b117f300-953a-11ea-80c8-c08aeeec52ae.png">
Hi, you mean this screen?

**Comment by alkhachatryan** [comment]
@mcrconference will get you back soon

**Comment by alkhachatryan** [comment]
@mcrconference which OS are you using on your server? You said it shared hosting? I couldn't reproduce it on my local / live machines.

**Comment by mcrconference** [comment]
Hi, this is our shared server : 
https://www.serverplan.com/hosting/linux/

**Comment by mcrconference** [comment]
hello this is our shared server : 
https://www.serverplan.com/hosting/linux/

**Comment by alkhachatryan** [comment]
Looks like your hosting provider blocked proc_open function.
Check this and  ask your hosting provider to enable it for you.

https://stackoverflow.com/questions/33401630/proc-open-has-been-disabled-for-security-reasons-php-error

**Comment by mcrconference** [comment]
hello, by activating the function you have reported to me the library works. I did some tests but if I run the php artisan commands I get this error. Can you help me ? Thanks for everything
![Screenshot_2020-05-18 Web Console](https://user-images.githubusercontent.com/65294947/82189226-56dab180-98ef-11ea-911e-f0384fd23163.png)

**Comment by alkhachatryan** [comment]
Hi.

Do you see error only for artisan commands?

Anyway thnk you for provided screenshot, will fix it

**Comment by mcrconference** [comment]
Hi, yes if I run the linux commands they work

**Comment by mcrconference** [comment]
Hello, did you manage to solve the problem?

**Comment by alkhachatryan** [comment]
@mcrconference  not yet

**Comment by homayoonahmadi** [comment]
I had this problem too. proc_open() , exec() and shell_exec() functions wasnt accessible for security reasons.

If you just want to use Artisan commands you can do this to make console working !

In `helper.php` file inside `vendor/alkhachatryan/laravel-web-console` directory change `execute_command($command)` function as below:

```
function execute_command($command)
{
    if (Str::startsWith($command, 'php artisan')) {
        $command = Str::replace('php artisan ', '', $command);
        $argv = explode(' ', $command);

        $args = array();
        for ($i = 1; $i < count($argv); $i++) {
            if (preg_match('/^--([^=]+)=(.*)/', $command, $match)) {
                $args[$match[1]] = $match[2];
            }
        }

        if (Str::startsWith($command, '--')) {
            $command = 'help';
            $args = $argv;
        }

        Artisan::call($command, $args);
        return Artisan::output();
    }



    $descriptors = [
        0 => ['pipe', 'r'], // STDIN
        1 => ['pipe', 'w'], // STDOUT
        2 => ['pipe', 'w'],  // STDERR
    ];

    $process = proc_open($command . ' 2>&1', $descriptors, $pipes);
    if (!is_resource($process)) {
        exit("Can't execute command.");
    }

    // Nothing to push to STDIN
    fclose($pipes[0]);

    $output = stream_get_contents($pipes[1]);
    fclose($pipes[1]);

    $error = stream_get_contents($pipes[2]);
    fclose($pipes[2]);

    // All pipes must be closed before "proc_close"
    $code = proc_close($process);

    return $output;
}
```

**Comment by homayoonahmadi** [comment]
@alkhachatryan I suggest you check if exec , shell_exec and proc_open are not accessible to user in the shared hosting server, then use Artisan:call() as I described in previous answer for `php artisan ...` commands. Cause many shared hostings prevent access to these functions for security reasons.

**Comment by alkhachatryan** [comment]
@homayoonahmadi do not change the file in vendors folder.
If you found a solution feel free to open a PR
