### ISSUE TITLE
Pre-Execute Comands

### ISSUE THREAD

**Issue by SOSkr** [alkhachatryan/laravel-web-console#18]
Is it possible to run commands before displaying the console?
I need to execute commands according to the server that the user selects

**Comment by alkhachatryan** [comment]
@SOSkr You can

**Comment by alkhachatryan** [comment]
@SOSkr Here is the request payload I got from my browser when executing the command from terminal. You can edit it and send to the server.

```
id: <Some number. May be 1>
jsonrpc: "2.0"
method: "run"
params: [
0: "<USER_NAME>:<HASHED_USER_PASS>"
1: {user: "<USER_NAME>", hostname: "<HOSTNAME>", path: "<PATH WHERE TO EXECUTE A COMMAND>"}
]
hostname: "<HOSTNAME>"
path: "<PATH WHERE TO EXECUTE A COMMAND>"
user: "<USER_NAME>"
2: "<COMMAND TO EXECUTE>"
```

**Comment by jiteshgolecha** [comment]
@alkhachatryan how to get the HASHED_USER_PASS?
