### ISSUE TITLE
"filter_pattern" not found or invalid function name (vendor/alkhachatryan/laravel-web-console/src/WebConsoleRPCServer.php:266)

### ISSUE THREAD

**Issue by Bushulyak** [alkhachatryan/laravel-web-console#19]
Tab дополняет только в текущей директории (ls storage [TAB] - работает), но при попытке (ls storage/logs [TAB]) выдает ошибку:

local.ERROR: array_filter(): Argument #2 ($callback) must be a valid callback, function "filter_pattern" not found or invalid function name {"exception":"[object] (TypeError(code: 0): array_filter(): Argument #2 ($callback) must be a valid callback, function "filter_pattern" not found or invalid function name at /var/www/chat/vendor/alkhachatryan/laravel-web-console/src/WebConsoleRPCServer.php:266)

если попытаться вынести этот метод из vendor - приходится выносить чуть ли не все оттуда, потому что много private свойств/методов

почему бы не передавать callback сразу функцией? зачем объявлять функцию в методе и передавать ее название?

**Comment by Bushulyak** [comment]
![image](https://user-images.githubusercontent.com/26183062/121689086-e17ae980-cacc-11eb-8b21-09fd35e9b92d.png)

**Comment by alkhachatryan** [comment]
@Bushulyak feel free to open a PR with your fixes.
