### ISSUE TITLE
[BUG] unable to open nano editor

### ISSUE THREAD

**Issue by queensherainfotech** [alkhachatryan/laravel-web-console#24]
I've just installed the library in my Laravel 8 project via composer, published the configuration, and changed the config.
I ran my project. it works great. but when I try to remove any file, I got permission denied error.
Also, while opening nano editor I got issues like, ***sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper***

**Screenshots**
![image](https://user-images.githubusercontent.com/57682399/154841556-7ea8a247-515c-411e-b30d-a9c737a76995.png)

**Comment by alkhachatryan** [comment]
You get permissions denied issue, because the user which ran the web service (probably apache, httpd, nginx) doesn't have a permission on that part.

About second message: use -S option  and see what happens

**Comment by queensherainfotech** [comment]
I provided 777 permission still got denial issue.
Also, tried nano editor with -S option still got issue (sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper).

**Comment by alkhachatryan** [comment]
@queensherainfotech I think this is more server configs related issue. I didn't get that issue on my local server and VPS.
Can you please contact hosting support?
