### ISSUE TITLE
Security Risk

### ISSUE THREAD

**Issue by rahulshukla-webkul** [alkhachatryan/laravel-web-console#4]
If Some delete the file from it, then whole application will be stop working,
Please see this one - https://prnt.sc/q2b4ot, https://prnt.sc/q2badv

**Comment by alkhachatryan** [comment]
Hi.

You're deleting the necessary files of application - index.php/vendor dir. After deleting these files whole application will stop to work, not only package

**Comment by alkhachatryan** [comment]
Added possibility to set a list of forbidden commands in the release: 
https://github.com/alkhachatryan/laravel-web-console/releases/tag/2.2
