### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by lexdubyna** [alkhachatryan/laravel-web-console#8]
When trying to login with correct credentials I get `Wrong password try again!`

The logs show the real error:
`Undefined offset: 2 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 2 at C:\\OSPanel\\domains\\crm\\vendor\\alkhachatryan\\laravel-web-console\\src\\LaravelWebConsole.php:60)`

**Comment by alkhachatryan** [comment]
Show me your config file

**Comment by lexdubyna** [comment]
Sorry for late reply.

```
<?php

return [
    'no_login' => false,
    'user' => [
        'name' => env('CONSOLE_USER_NAME', 'root'),
        'password' => env('CONSOLE_USER_PASSWORD', 'root'),
    ],
    'accounts' => [],
    'password_hash_algorithm' => '',
    'home_dir' => '',
];
```

**Comment by alkhachatryan** [comment]
> Sorry for late reply.
> 
> ```
> <?php
> 
> return [
>     'no_login' => false,
>     'user' => [
>         'name' => env('CONSOLE_USER_NAME', 'root'),
>         'password' => env('CONSOLE_USER_PASSWORD', 'root'),
>     ],
>     'accounts' => [],
>     'password_hash_algorithm' => '',
>     'home_dir' => '',
> ];
> ```

The problem is here:
![image](https://user-images.githubusercontent.com/22774727/74373511-0e928b80-4df6-11ea-8ab6-37a52569c8f5.png)

Check the command you send

**Comment by lexdubyna** [comment]
I installed `laravel-web-console` on a clean new Laravel project and I didn't change any request settings. I just go to console page, enter login and password and it doesn't work.
BTW, `'no_login' => true,` doesn't disable login, I still have to enter login and password (which doesn't work either).

**Comment by alkhachatryan** [comment]
@lexdubyna check new release please. In case of the issue still be there, feel free to open a PR
